# These are supported funding model platforms

github: [guofei9987]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: guofei9987 # Replace with a single Open Collective username
微信打赏: https://www.guofei.site/public/donate/WeChatQR.jpg
