# These are supported funding model platforms

custom: ["https://www.guofei.site/public/donate/WeChatQR.jpg","https://www.guofei.site/public/donate/AliPayQR.jpg"]
open_collective: guofei9987 # Replace with a single Open Collective username
